# Generated by Django 4.1.2 on 2022-10-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='catrgory',
            new_name='category',
        ),
    ]
